apiVersion: apps/v1
kind: Deployment
metadata:
  name: yhyghgd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yhyghgd
  template:
    metadata:
      labels:
        app: yhyghgd
    spec:
      containers:
      - image: okteto.dev/yhyghgd:latest
        name: yhyghgd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "e2b49ed9-6fc0-4ea8-9136-77e83abb8bfc"
        - name: Vless_Path
          value: "/e2b49ed9-6fc0-4ea8-9136-77e83abb8bfc-vless"
        - name: Vmess_UUID
          value: "e2b49ed9-6fc0-4ea8-9136-77e83abb8bfc"
        - name: Vmess_Path
          value: "/e2b49ed9-6fc0-4ea8-9136-77e83abb8bfc-vmess"
        - name: Share_Path
          value: "/v2yhujnk"
